-- phpMyAdmin SQL Dump
-- version 4.6.5.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 23, 2017 at 06:17 PM
-- Server version: 10.1.21-MariaDB
-- PHP Version: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `secure_bharat`
--

-- --------------------------------------------------------

--
-- Table structure for table `quiz`
--

CREATE TABLE `quiz` (
  `question_id` int(11) NOT NULL,
  `question_no` int(11) NOT NULL,
  `question_name` text NOT NULL,
  `option1` text NOT NULL,
  `option2` text NOT NULL,
  `option3` text NOT NULL,
  `option4` text,
  `correct_option` int(11) NOT NULL,
  `complete_answer` text NOT NULL,
  `image_path` varchar(250) DEFAULT NULL,
  `question_categary` varchar(30) DEFAULT NULL,
  `question_level` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `quiz`
--

INSERT INTO `quiz` (`question_id`, `question_no`, `question_name`, `option1`, `option2`, `option3`, `option4`, `correct_option`, `complete_answer`, `image_path`, `question_categary`, `question_level`) VALUES
(1, 1, 'Which one of the following did cybercriminals really do?', 'They took control over the Port of Antwerp computer systems for two years for a drug cartel.', 'hey caused a single-day 7-point drop in the New York Stock Exchange.', 'They turned off the alarm at the Isabella Stewart Gardner Museum and stole the only seascape created by Rembrandt.', NULL, 1, 'Round 2011 they gained control over the port systems. For 24 months, the group released containers to their own truckers without the port authorities knowing and then removed information about contraband containers from all databases. When police uncovered the case, they also discovered a ton of cocaine, guns, and more than 1.3 million Euro in a suitcase.', 'images/image1.jpg', '', 0),
(2, 2, 'When hackers leaked data from the Ashley Madison dating site in 2015, everybody found out that:', 'All of the women on Ashley Madison were blonde.', 'The former Prime Minister of Great Britain, Tony Blair, used the site for secret affairs.', '70,000 of the women on the website were actually bots.', NULL, 3, 'Gizmodo authors analyzed the leaked database and discovered that the company created the legion of bots and taught them to flirt with visitors — to “create the illusion of a vast playland of available women.” This discovery pissed off a lot of people and almost destroyed Ashley Madison’s reputation.', 'images/image2.jpg', '', 0),
(3, 3, 'Fact or fiction: Which of the following actually happened?', 'A guy checked out of a hotel, returning his hotel key card. Criminals who checked in after him used the card to steal his money.', 'A computer was infected by a virus that caused it to overheat and then explode.', 'A family’s life became a darknet reality show after hackers broadcast the stream from a hacked baby monitor.', NULL, 3, 'toward the end of 2014, security experts discovered a website broadcasting videos from hundreds of hacked baby monitors. There was even an anonymous forum where people could discuss “funny” screenshots taken with hacked cameras. Chilling! This was one of many instances of criminals hacking baby monitors and webcams to spy on people.', 'images/image3.jpg', '', 0),
(4, 4, 'You connect to public Wi-Fi to buy gifts online and chat with your friends. What’s the worst that can happen?', 'Hackers will intercept your credentials and steal the money in your banking account.', 'Your battery will discharge.', 'Nothing bad will happen — I do it all the time.', NULL, 1, 'Criminals use public Wi-Fi to intercept the financial and private data of the people who connect to open hotspots.', 'images/image4.jpg', '', 0),
(5, 5, 'How can I hide from facial recognition?', 'Live underground. Say hi to the ninja turtles!', 'Get an asymmetrical haircut and put on radiant make-up.', 'Light your face with red flashlight.', NULL, 2, 'There really are some makeup and haircutting techniques that drive facial recognition systems crazy. If you know them all, you can be sure that even if Big Brother is watching you, you’ll never be caught flat-footed!', 'images/image5.jpg', '', 0),
(6, 6, 'Why are iris and fingerprint sensors considered unreliable protection for smartphones?', 'Modern computers allow brute forcing of people’s fingerprints and iris patterns.', 'In fact, there are people with identical irises and fingerprints.', 'Photo of your eye and hand in high resolution can be used to fool even modern sensors.', NULL, 3, 'Unfortunately, photography is far ahead of biometric protection — a good photo can deceive even the newest sensors.', 'images/image6.jpg', '', 0),
(7, 7, 'What kind of malware reached the International Space Station?', 'A keylogger developed by hackers from North Korea.', 'A password-stealing worm meant to target online gamers.', 'A simple virus written as a training exercise by astronauts. It was no big deal, but the media made a fuss about it.', NULL, 2, 'In 2008 they found malware in space! Fortunately, there was no threat to the command-and-control systems at the space station.', 'images/image7.jpg', '', 0),
(8, 8, 'Stuxnet is well known because:', 'It was created to sabotage Iran’s nuclear program.', 'In 2012, it was the first worm to infect a train.', 'This “white” malware fixed vulnerabilities instead of exploiting them.', NULL, 1, 'Stuxnet was the first malware to bring physical damage to critical infrastructure. It made uranium enrichment centrifuges inoperable.', 'image/image8.jpg', '', 0),
(9, 9, 'All security experts know about Morris worm. Why?', 'In addition to huge companies, this unusual malware targeted leading math and cryptography specialists.', 'his old worm went out of control and caused enormous damage — between $100,000 and $10,000,000.', 'The Carbanak band used this malware to steal more than a billion dollars from financial organizations all over the world.', NULL, 2, 'The Morris worm is the first virus in history to infect 10% of the world’s PCs. It also resulted in the first felony conviction in the US under the 1986 Computer Fraud and Abuse Act.', 'images/image9.jpg', '', 0),
(10, 10, 'Cyber security fact: Oracle Java, Adobe Reader or Adobe Flash is present on 99% of computers. That means that 99% of computer users are vulnerable to exploit kits (software vulnerabilities).\r\n\r\nWhy?', 'Because the vulnerabilities that these types of software often present are extremely critical: all it takes is one click on an infected advertising banner to give a hacker full access to your computer.', 'Outdated software reduced the speed of processor.', 'these software does not have further support from the software provider. ', NULL, 1, 'Adobe Flash has a huge number of vulnerabilities, so cyber criminals target it in the majority of their attacks. By using these security holes in Flash, attackers can infect your computer with ransomware, such as various CryptoLocker variants or Teslacrypt and CTB-Locker.', 'images/image10.jpg', '', 0),
(11, 11, 'Which type of act does not come in the insider attack?', 'when a employee resigns on the spot without providing any notice?', 'Exploited insiders, who  may be “tricked” by external parties into providing data or passwords they shouldn’t.', 'Careless insiders may simply press the wrong key and accidentally delete or modify critical information.', NULL, 1, 'If a soon-to-be-ex-colleague decides to do some damage before he/she leaves the company, make sure your work goes unaffected.\r\nBe careful how you manage your passwords: use a password management application, use strong passwords and change them regularly.\r\nProtect your shared documents and keep updated backups of all the information you’re working on.', 'images/image11.jpg', '', 0),
(12, 12, 'People are the weakest link when it comes to cyber security, which is why psychological manipulation of cyber attack victims is so common.\r\nCan you related it is why ?', 'people\'s can click any strange links and know what a phishing attack looks like.\r\nand install software from untrusted sources.\r\n', 'trust people blindly and don’t give away confidential information to strangers.', 'both of above', NULL, 3, 'According to the definition, social engineering, in the context of information security, refers to psychological manipulation of people into performing actions or divulging confidential information. This is a type of confidence trick for the purpose of information gathering, fraud, or system access, and the first type of attack of this kind known in history is the Trojan horse itself (not the computer virus, but the Greek mythical event).', 'images/image12.jpg', '', 0),
(13, 13, 'How can you protect against government surveillance ?', 'Use a VPN solution and encryption technology to protect your confidential information.', 'Using incognito mode browsing.', 'use an antivirus, so that you become invincible to the government.', NULL, 1, 'Government malware accelerates the evolution of criminal malware – cyber criminals do a lot of reverse engineering on government malware, and use its tactics and technical approach to create new, more advanced malware of their own.\r\nGovernments have fortified zero day vulnerability black markets – Zero Day vulnerabilities auctions have become common, but governments are buying the intelligence related to these vulnerabilities and weapon zing them, instead of disclosing them responsibly, as is the norm in the cyber security industry.\r\nGovernments try to restrict/backdoor/break encryption – in the name of transparency and protection against cyber criminals and terrorists, governments all over the world are trying to limit every individual’s right to encrypt confidential information. This is why “cyber policies” can do more damage than good.', 'images/image13.jpg', '', 0),
(14, 14, 'Which of the following is not considering the hacktivism ?', 'a politically motivated technology hack.', 'allegation from one political organisation on another.', 'use of computers and computer networks to promote a political agenda.', NULL, 2, 'Hacktivism accounts for half of the cyber attacks launched in the world. The term represents a subversive use of computers and computer networks to promote a political agenda. With roots in hacker culture and hacker ethics, its ends are often related to the free speech, human rights, or freedom of information.', 'images/image14.jpg', '', 0),
(15, 15, ' the most expensive virus in the world and in cyber security history, having caused an estimated financial damage of $38.5 billion! It is transmitted as', 'Tapeworms', 'EarthWorm', 'e-mail worm', NULL, 3, 'Mydoom was mainly transmitted by email, disguised as spam email. A user might inadvertently open the attachment in the email and the worm would re-send itself to every address it could find. The original version contained a payload that did two things: it opened a backdoor into the user’s computer, allowing remote control of it, while also conducting a DDoS attack (Direct Denial Of Service) against SCO group’s website.', 'images/image15.jpg', '', 0),
(16, 16, 'Social engineering – cyber criminals’ favorite way to manipulate victims. Why?', 'Because it only need computer to manipulate victims. ', 'It is based on the basic hardware knowledge.', 'People are the weakest link.', NULL, 3, 'People are the weakest link when it comes to cyber security, which is why psychological manipulation of cyber attack victims is so common.\r\n\r\nAccording to the definition, social engineering, in the context of information security, refers to psychological manipulation of people into performing actions or divulging confidential information. This is a type of confidence trick for the purpose of information gathering, fraud, or system access, and the first type of attack of this kind known in history is the Trojan horse itself (not the computer virus, but the Greek mythical event).', 'images/image16.jpg', '', 0),
(17, 17, 'Passwords are strings of characters used to access online services (e.g. your email or social networks profile).\r\nHowever they also help to prevent other people from accessing your personal accounts. Unfortunately, because we use so many services, it is difficult to remember each password that we have.\r\nIn this situation, what could be a good strategy?', 'I save all my different passwords in a file: when I need one, I can easily retrieve it.', 'I still prefer to use a different password each time.', 'I still prefer to use a different password each time.', NULL, 3, 'Having different passwords for each service, not saving them in any file, is the correct strategy for securing one’s own accounts. Indeed, if you choose the same password for all your services, then in case that a malicious user manages to learn your password from one service, he/she will have access to all your accounts in all services. Furthermore, it is important to have strong passwords having adequate length (i.e. at least 8 characters) composed of both lower and upper case letters, as well as numbers and non-alphanumeric characters.\r\n\r\nFor more information, including ideas to choose strong passwords that you can remember, you may see here:', 'images/image17.jpg', '', 0),
(18, 18, 'While opening the email, you got an interesting but suspicious message from a company.\r\nThe message said that “you’ve won the lottery” and the company was asking you specific personal and banking details so that they could lodge a large sum of money in your bank account.\r\nThese emails are a common type of cyber-attack that goes by the name of…..', 'Phishing', 'Spyware', 'Spoofing', NULL, 1, 'This is the correct answer. With Phishing an attacker tries to collect user personal data (such as passwords and credit card numbers) by means of fake apps, fake SMS or fake email messages that seem genuine. The attacker may either ask you to provide your data directly (i.e. via replying in the mail) or via visiting a web site that he/she proposes. Never answer a message that appears to be phishing.', 'images/image18.jpg', '', 0),
(19, 19, 'How many times a week do you read an article on cyber security and hacking?\r\nAlthough both are popular buzzwords they are also of paramount importance in our daily life at work or during our spare time.Generally, <br/>who are hackers?', 'They are benign computer experts.', 'They are malicious computer criminals.', 'Hackers could be both benign computer experts and malicious computer criminals', NULL, 3, 'This is correct since hackers could be both benign and malicious. In fact, hackers are persons with high technical skills and possessing high degree of knowledge, being able to get unauthorized access into protected systems and assets. However, the term can have different meanings depending on the context in which it is used. The common distinction is between ‘white hat hackers’ (benign) and ‘black hat hackers’ (malicious) or between ‘hacking for good’ (e.g. to assess and test security) and ‘hacking for bad’ (e.g. for criminal activities). Usually, bad hackers are being referred to as crackers.', 'images/image19.jpg', '', 0),
(20, 20, 'One day you were listening to the evening news while preparing your dinner at home.\r\nOn the TV show the journalist was interviewing a computer industry expert talking about the importance of regularly updating and patching computer operating systems for security reasons. However you were distracted by cooking and could not understand why he was insisting on that.\r\n\r\nWhen thinking about it the day after, you think that patching the operating system…', 'Fixes problems and makes the operating system more secure.', 'Allows you to continue using your software without paying.', 'Improves the working functions of my operating system.', NULL, 1, 'Patching the operating system is usually a way to fix bugs and security problems for your computer. Keeping your operating system updated is a good strategy that helps to secure your computer and, thus, your data.', 'images/image20.jpg', '', 0),
(21, 21, 'Malware is software that has a malicious intent to harm users and their devices.\r\nA relevant protection in these cases is to have an antivirus software installed. However, even this is not sufficient as the antivirus needs to be constantly updated.\r\n\r\nWhat is your perspective about the need for updating the antivirus?', 'I Updating of my antivirus should be performed only if I don’ t regularly patch my operating system.', 'The antivirus update protects my computer from newly created malware.', 'The antivirus updates ensure the correct performance of my computer.', NULL, 2, 'This is the correct answer. Antivirus updates do offer you the latest protection against new forms of malware. This would normally include ‘signature files’ of new malware, i.e. information for identifying malware. Hence, antivirus should be updated very frequently – preferably, on a daily basis. Note that although patching your operating system is also important for security, this does not protect you for all new malware – that’s why you need to update your antivirus', 'images/image21.jpg', '', 0),
(22, 22, 'On your personal laptop you have been using some of the same computer programs for years.\r\nOne of your friends, who is an expert in security, noticed that one of your programs has long been discontinued by the manufacturer. Your friend told you that this old and discontinued software exposes your computer to serious security threats.\r\n\r\nAmong these threats your friend mentioned…..', 'The Dark Net', 'Malicious Software', 'Privacy Invasions', NULL, 2, 'his is the correct answer indeed. Using discontinued software implies exposure to a number of risks such as malicious software (malware) due to the software lacking updates. See for more information and additional threats coming from the use of discontinued software a recent ENISA recommendation: Users should make sure that they are aware and understand the security risk they are exposing themselves to by continuing to use obsolete software.', 'images/image22.jpg', '', 0),
(23, 23, 'You are a ‘very heavy’ user of mobile apps. You have apps that are being used by your kids for playing and learning.\r\nYou have apps that you use in your leisure time for staying informed about what happens in your city. You have apps that you use to keep in touch with your friends. Whenever you see an interesting app you want it and your instinct is just to download and install it.\r\n\r\nHowever for ensuring your safety and security it is best to…', 'Make sure you do not incur hidden costs when downloading an app.', 'Check that the app comes from a reputable source.', 'Avoid having too many apps installed.', NULL, 2, 'This is the correct answer. Before installing or using new smartphone apps or services, it is important to check their reputation. Never install any software onto the device unless it is from a trusted source. Also, make sure that, especially if the app is cost-free, you fully understand which personal data it uses and make sure that you agree with this.', 'images/image23.jpg', '', 0),
(24, 24, 'These days in the media it is not uncommon to hear that organisations and companies have suffered from cyber-attacks.\r\nThe popular image is that these attacks are carried out by so-called malicious hackers that are external to an organisation. However several observations show that many of these attacks are carried out by organisation employees/officers or former employees.What is the common name which is given to this latter type of threat?', 'Ethical hacking', 'Trolling', 'Insider Threat', NULL, 3, 'This is the correct answer indeed. While it is common to think that cyber-attacks come from external sources, often attacks come from the inside. The insider threat – for example an employee - might obtain access to the computer systems or networks of an organisation, and then conduct harmful or criminal activities against the organisation. However a significant amount of insider threats stem from unintentional user errors/mistakes.', 'images/image24.jpg', '', 0),
(25, 25, 'You have noticed that your computer is acting erratically and normal tasks (e.g., open a document/application), are taking a little bit longer to perform.\r\nSo you called a friend of yours who is a computer technician and always helps you when your computer has problems. After a careful inspection he told you that your computer has been infected by a ‘Trojan Horse’.\r\n\r\nYou wonder what a ‘Trojan Horse’ could be?', 'It is a computer virus that frequently attack computers.', 'It is a malicious software that allows other programs to control your computer by misleading users of its true intent.', 'It is a malfunction of the software that makes it difficult to navigate the Internet.', NULL, 2, 'This is the correct answer. A Trojan horse is an autonomous program that appears to be doing what the user wants, but is actually doing something else. Hence, this unwanted, hidden, additional function could allow other programs to control your computer by misleading users of its true intent. A characteristic example of a Trojan Horse is the case with the AIDS Trojan that encrypted the user’s data after a number of reboots', 'images/image25.jpg', '', 0),
(26, 26, 'which of the following can\'t help you in preventing e-mail threats ?', 'Use e-Mail filtering software to avoid Spam so that only messages from authorized users are received', 'Ignore e-mails from strangers', 'Click on the e-Mails that you receive from un trusted users, for executing some code.', NULL, 3, 'Avoid sending personal information through e-Mails.<br>\r\nAvoid filling forms that come via e-Mail asking for your personal information and do not click on links that come via e-Mail.<br>\r\nDo not click on the e-Mails that you receive from un trusted users as clicking itself may execute some malicious code and spread into your system.', 'images/image26.jpg', '', 0),
(27, 27, 'how information sending by email help in stealing credit card information ?', 'E-mails are not secured.', 'The compromise can occur by many common routes and can usually be conducted without tipping off the card holder.', 'Someone can easily hacked your email account and use your credit card information.', NULL, 2, 'Credit card fraud is a wide-ranging term for theft and fraud committed using a credit card or any similar payment mechanism as a fraudulent source of funds in a transaction. The purpose may be to obtain goods without paying, or to obtain unauthorized funds from an account. Credit card fraud is also an adjunct to identity theft.', 'images/image27.jpg', '', 0),
(28, 28, 'Which of the following not a browsing risk?', 'Phishing (spoofing)', 'Earthquake', 'Pop-ups', NULL, 2, 'Pop-ups are a small windowpane that opens automatically on your browser. Generally, they show advertising, which can be from legitimate company, but also may be scams or dangerous software.\r\n\r\nspoofing is a term used to describe methods of faking various parts of the browser user interface. This may include the address or location bar, the status bar, the padlock, or other user interface elements', 'images/image28.jpg', '', 0),
(29, 29, 'Which of the following is good for making yourself secured ?', 'Sharing of password to the close friends and family.', 'Share your every emotions on social media in the form of text, images etc. ', 'By taking care of privacy policies of different social platforms', NULL, 3, 'Hacker\'s can\'t steal your personal data.\r\nPossibility of Cyber bullying is reduced. ', 'images/image29.jpg', '', 0),
(30, 30, 'What is the cyber security?', 'Install a smoke alarm.', 'Lock on your home door.', 'Protecting your informations.', NULL, 3, 'Cybersecurity is the body of technologies, processes and practices designed to protect networks, computers, programs and data from attack, damage or unauthorized access.', 'images/image30.jpg', '', 0),
(31, 31, 'When is the best time to lie to your information security auditor or officer?', 'If you want to cover up your best friend’s faults or mistakes ', 'If it impacts the termination of the key people in your organization', 'none of the above', NULL, 3, 'This is a very tricky question and it has been used in some technical and security interviews. You should never lie to your information security auditor or officer since their role is to maintain the confidentiality, integrity, and availability (CIA triad) of the assets and technologies of your organization or company. A good information security auditor or officer can help you about the cyber security problems in your organization. Even if you lost key people in your organization because of their wrongdoings – do not cover them up. There is a due process in a good organization or company.', 'images/image31.jpg', '', 0),
(32, 32, 'Which of the following is an fact of cyber bullying.', 'Cyberbullying can happen 24 hours a day, 7 days a week, and reach a kid even when he or she is alone. It can happen any time of the day or night.', 'Cyberbullying messages and images can be posted anonymously and distributed quickly to a very wide audience. It can be difficult and sometimes impossible to trace the source.', 'Both of them', NULL, 3, 'Cyberbullying is bullying that takes place using electronic technology. Electronic technology includes devices and equipment such as cell phones, computers, and tablets as well as communication tools including social media sites, text messages, chat, and websites', 'images/image32.jpg', '', 0),
(33, 33, 'You came across a website that looks exactly like Facebook but it has a different domain which you have never heard of, which of the following is the best course of action that should be taken?', 'Hack that website and deface it then post it on Facebook or Twitter.', 'Launch DDoS (Distributed Denial of Service) attacks into that website with the help of your friends if you can’t hack it in order to take it offline then post it in Facebook or      Twitter. #TangoDown!', 'Do not login into that website and report it as a phishing page to Google Safe       Browsing Team – https://www.google.com/safebrowsing/report_phish/.', NULL, 3, 'This is a possible phishing attempt which could harm other cyber citizens because the website could store the login credentials if the user is not that cyber-savvy. As a concerned cyber citizen, you need to be vigilant but don’t hack it or launch DDoS attacks on it instead report it to security teams or computer emergency response teams like the Google Safe Browsing Team, US-CERT, etc. By hacking and DDosing it, you are being unethical.', 'images/image33.jpg', '', 0),
(34, 34, 'While visiting your favorite website for downloading the Firefox browser, a popup appears that says “You just won 100,000 US dollars! Click this link to claim your prize”, what should you do?\r\n\r\n', 'Share the link to your friends, classmates and colleagues so that they could also claim the prize because sharing is caring.', 'Report the popup and the details to the website administrator and don’t download the Firefox browser.', 'Click the popup and claim your prize.', NULL, 3, 'There are two possibilities of what just happened here. The website could be hacked and backdoored wherein the attacker placed a malicious link or the website administrator didn’t fully review the advertising ads he or she placed on the website. You should inform the website administrator and explain to him or her that this could harm other computer users who are not that vigilant.', 'images/image34.jpg', '', 0),
(35, 35, 'Your college best friend has just sent you a chat in Facebook and sent with a link. The link is a shortened URL for example https://goo.gl/wf4V8Z, what should you do?', 'Click the link because it shouldn’t be malicious since he/she is your best friend after all. There is nothing to worry about.\r\n', 'Do not click the link and try to check the URL using an online tool that checks where it really takes you.', 'Contact your local Computer Emergency Response / Readiness Team because it may contain malicious software.', NULL, 2, 'The shortened URL could take you to a malicious website which could steal your cookies, exploit the trust of your browser, or exploit the vulnerability of your browser wherein the attacker can then control your computer (check out BeeF or Metasploit video tutorials on how an attacker could control your PC if you want to know more). The best way to ensure that it will take you to a legitimate site is to use an online URL expander like http://longurl.org/. If it takes you to an unknown website or if you suspect that the website is malicious report it.', 'images/image35.jpg', '', 0),
(36, 36, 'You went to Starbucks to buy a coffee and then while waiting for your order, you decided to connect to their Free WIIFI. While browsing to your Google Mail (https://mail.google.com/), the page redirects to http://www.googlemail.rahul.net. What do you think should you do?', 'Login to where Google Mail has redirected, it’s just one of Google’s web sites – not suspicious at all.', 'Disconnect to Starbuck’s WIFI network.', 'Find the Wireless Access Point and reboot it', NULL, 2, 'Someone maybe conducting ARP spoofing and routing all the Google Mail traffic to http://www.googlemail.rahul.net so it’s wise to just disconnect to their WIFI connection or else your Gmail credentials will be sniffed. It would also be wise to approach their IT personnel about their problem. http://www.googlemail.rahul.net is possibly owned by the attacker. For me, it’s wise not to connect to Free WIFI networks and be partially paranoid about where you connect to.', 'images/image36.jpg', '', 0),
(37, 37, 'Why is backing up data files important?', ' Backups ensure that the information you need is there when you need it', 'f the information is damaged it can be recovered ', 'both of the above', NULL, 3, 'The Importance of Backing Up Files. It is very important to do regular backups to prevent the lost of data. Software can be reinstalled but your data could quite possibly be lost for ever. There are various causes for data loss, machine breakdown, virus, power outage, software upgrades, fire, flood and human error.', 'images/image37.jpg', '', 0),
(51, 51, 'Social networking on websites can be a fun and convenient way to meet people and stay connected. What information do you include on your social networking profile? ', 'My date of birth, including the year', 'My phone number My physical address', 'None of this information appears publicly on my profile', NULL, 3, '', 'images/image51.jpg', '', 0),
(52, 52, 'Which of the following kinds of documents  you should shred before throwing away? ', 'Cancelled checks,Financial statements,Expired bank cards ', 'Transaction and ATM receipts,Unwanted credit offers', 'Both of the above', NULL, 3, '', 'images/image52.jpg', '', 0),
(53, 53, 'Which of the following statements is true?', 'I receive my financial information (bank statements, credit card statements, checks, or other notices) online or in a secure mailbox.', 'I review financial statements or account activity online regularly and report any discrepancies or suspicious transactions immediately.\r\n', 'None of the above', NULL, 3, 'Generally,everyone among us do the same mistakes everyday.', 'images/image53.jpg', '', 0),
(54, 54, 'Choose which of the following things you do ?', 'I change my password regularly (every 30 to 60 days).', 'I use my date of birth, Social Security number, or other personal information for my password.\r\n', 'I choose passwords that contain a combination of letters, numbers, and special characters.\r\n', NULL, 3, '', 'images/image54,jpg', '', 0),
(56, 56, 'Mobile banking applications are programs you can download to your mobile device. If you have suspicions about the authenticity of a mobile banking app, what should you do? ', 'ownload it anyway because tools on the Web are always safe', 'Contact the financial institution for instructions on how to access its mobile app', 'Conduct your banking through the official mobile website instead of using the app', NULL, 3, 'Mobile banking is a service provided by a bank or other financial institution that allows its customers to conduct financial transactions remotely using a mobile device such as a mobile phone or tablet. It uses software, usually called an app, provided by the financial institution for the purpose. Mobile banking is usually available on a 24-hour basis. Some financial institutions have restrictions on which accounts may be accessed through mobile banking, as well as a limit on the amount that can be transacted.', 'images/image56.jpg', '', 0),
(59, 59, 'What is the most common delivery method for viruses?', 'Email', 'Instant Message', 'Internet download and Portable media', NULL, 1, 'To avoid contact with a virus it’s important to exercise caution when surfing the web, downloading files, and opening links or attachments. As a best practice, never download text or email attachments that you’re not expecting, or files from websites you don’t trust.', 'images/image59.jpg', '', 0),
(60, 60, 'Which statement most accurately describes virus?', 'A program that is secretly installed onto your computer and makes copies of itself which consumes your computer resources', 'A program that protects your computer from hackers', 'A program that is installed onto your computer that monitors your internet use', NULL, 1, 'A computer virus, much like a flu virus, is designed to spread from host to host and has the ability to replicate itself. Similarly, in the same way that viruses cannot reproduce without a host cell, computer viruses cannot reproduce and spread without programming such as a file or document.', 'images/image60.jpg', '', 0),
(61, 61, 'Which of the following is a measure for preventing a social engineering attack except:', 'Do not give out computer or network information', 'Do not complete confidential company tasks in an unsecure setting', 'Do not secure sensitive documents and media', NULL, 3, 'At the root of many ransomware attacks is the art of social engineering, which involves manipulating a person or persons in order to access corporate systems and private information. Social engineering, widely used in ransomware crimes, plays into human nature’s inclination to trust. For hackers, it is the easiest method for obtaining access to a private system. After all, why would anyone spend the time trying to guess someone’s password when they can simply ask for it themselves?', 'images/image61.jpg', '', 0),
(62, 62, 'What should you do if you think your password has been compromised?', 'Change your password and report the incident to the proper authorities - such as a system administrator(s)', 'Check other systems that you have accounts on as they may be compromised as well', 'All the above', NULL, 3, 'Whenever Your account get breached. Block access to your credit report. Use different passwords for all online accounts. ', 'images/image62.jpg', '', 0),
(63, 63, 'While visiting your favorite website for downloading the Firefox browser, a popup appears that says “You just won 100,000 US dollars! Click this link to claim your prize”, what should you do?', 'Ignore that popup and just download the Firefox browser.', 'Click the popup and claim your prize.\r\nShare the link to your friends, classmates and colleagues so that they could also claim the prize because sharing is caring.', 'Report the popup and the details to the website administrator and don’t download the Firefox browser.', NULL, 3, 'There are two possibilities of what just happened here. The website could be hacked and backdoored wherein the attacker placed a malicious link or the website administrator didn’t fully review the advertising ads he or she placed on the website. You should inform the website administrator and explain to him or her that this could harm other computer users who are not that vigilant.', 'images/image63.jpg', '', 0),
(64, 64, 'You came across a website that looks exactly like Facebook but it has a different domain which you have never heard of, which of the following is the best course of action that should be taken?', 'Do not login into that website and report it as a phishing page to Google Safe       Browsing Team – https://www.google.com/safebrowsing/report_phish/.', 'Just ignore that website and login to https://facebook.com instead.', 'Hack that website and deface it then post it on Facebook or Twitter.', NULL, 1, '', 'images/image64.jpg', '', 0),
(65, 65, 'Your college best friend has just sent you a chat in Facebook and sent with a link. The link is a shortened URL for example https://goo.gl/wf4V8Z, what should you do?', 'Click the link because it shouldn’t be malicious since he/she is your best friend after all. There is nothing to worry about', 'Do not click the link and try to check the URL using an online tool that checks where it really takes you.Or install antivirus software, then click the link.', 'Contact your local Computer Emergency Response / Readiness Team because it may contain malicious software.', NULL, 3, 'The shortened URL could take you to a malicious website which could steal your cookies, exploit the trust of your browser, or exploit the vulnerability of your browser wherein the attacker can then control your computer (check out BeeF or Metasploit video tutorials on how an attacker could control your PC if you want to know more). The best way to ensure that it will take you to a legitimate site is to use an online URL expander like http://longurl.org/. If it takes you to an unknown website or if you suspect that the website is malicious report it.', 'images/image65.jpg', '', 0),
(66, 66, 'You went to Starbucks to buy a coffee and then while waiting for your order, you decided to connect to their Free WIIFI. While browsing to your Google Mail (https://mail.google.com/), the page redirects to http://www.googlemail.andrew.net. What do you think should you do?', 'Login to where Google Mail has redirected, it’s just one of Google’s web sites – not suspicious at all.', 'Disconnect to Starbuck’s WIFI network.', 'Find the Wireless Access Point and reboot it', NULL, 2, 'Someone maybe conducting ARP spoofing and routing all the Google Mail traffic to http://www.googlemail.andrew.net so it’s wise to just disconnect to their WIFI connection or else your Gmail credentials will be sniffed. It would also be wise to approach their IT personnel about their problem. http://www.googlemail.andrew.net is possibly owned by the attacker. For me, it’s wise not to connect to Free WIFI networks and be partially paranoid about where you connect to.', 'images/image66.jpg', '', 0),
(67, 67, 'What is the generic term for computer programs that can wreak havoc on your devices?', 'Malware', 'Damagedroids', 'Rudebots', NULL, 1, 'Malware (or malicious software) is the term for destructive programs which can do some serious damage to your devices in all sorts of ways, or can steal your personal information', 'images/image67.jpg', '', 0),
(68, 68, 'What is spyware?', 'When a cybercriminal takes on your identity', 'Software that collects data from your computer', 'A website that sells on personal data', NULL, 1, 'Spyware is the term for malicious software which collects personal information from your devices. Some spyware can record everything you say without you knowing.', 'images/image68.jpg', '', 0),
(69, 69, 'What is phishing?', 'Where criminals try to hack into your wireless network', 'Where criminals try to obtain sensitive information by presenting themselves as a trustworthy source', 'A pleasant weekend activity by the river', NULL, 2, 'Phishing is the name given to an attempt to gather personal information, generally for malicious reasons, by posing as trusted contacts or companies.Always be careful when you receive an email asking for information or telling you to follow a link. Always check with the supposed sender that it really is from them', 'images/image69.jpg', '', 0),
(70, 70, 'Which of these is an example of a phishing email?', '‘Your bank account has been compromised. Login here to protect yourself.’', '‘You have won the lottery! Follow this link to claim!’', 'Both', NULL, 3, 'Scammers will use every trick in the book to get you to hand over personal details or open a malicious web address. If it sounds too good to be true or is meant to scare you then think again! ', 'images/image70.jpg', '', 0),
(71, 71, 'When do you need to use anti-virus software?', 'As soon as you feel unwell', 'All the time, on your laptop only – and make sure it’s regularly updated', 'All the time, on all web-connected devices – and make sure it’s regularly updated', NULL, 3, 'Secure website addresses begin with https:// not just http:// (the s stands for secure) and feature a padlock icon in the address bar. Criminals can make their websites look very professional so be cautious even if everything looks in order', 'images/image71.jpg', '', 0),
(72, 72, 'Which of these is an indicator that a website is secure?', 'The web address starts with https://', 'The URL includes the company name and the webpage shows the company logo', 'You found the address on a search engine or as a link in an email', NULL, 1, 'HTTP VS HTTPS. Hyper Text Transfer Protocol Secure (HTTPS) is the secure version of HTTP, the protocol over which data is sent between your browser and the website that you are connected to. The \'S\' at the end of HTTPS stands for \'Secure\'. It means all communications between your browser and the website are encrypted.', 'images/image72.jpg', '', 0),
(73, 73, 'Which of these was NOT one of the most common passwords of 2015?', 'hello', 'password', '123456', NULL, 3, 'hello wasn’t one of the most popular passwords, whilst the other options all made it into the top 10. But for the FIFTH year running 123456 was the most popular (and therefore most guessable) password', 'images/image73.jpg', '', 0),
(74, 74, 'What is the best password policy?\r\n', 'Use the same, easy-to-remember password you have had for the past 10 years for every account.Something personal, like your pet’s name or your date of birth', 'Have a selection of different passwords and write them down somewhere so you don’t forget them', 'Be vigilant – never use the ‘remember password’ prompt and have different complex passwords for each account', NULL, 3, 'Your food choices should be a safe talking point - although it’s probably best not to tag your location! Social media is a minefield. People can know when you are not home if you say when you are off on holiday or make an educated guess at your password from personal information like your pet’s name. The best thing to do is keep your accounts private and be careful about what you share online.', 'images/image74.jpg', '', 0),
(76, 76, 'Which of these is the least risky to talk about on social media?', 'Your exciting holiday plans', 'Your new phone number', 'What you had for your quiet Sunday lunch at home', NULL, 3, 'Most children nowadays spend a lot of time online and much of what they do is safe and age-appropriate. But as we all know, it is important to take measures to protect your family from danger – both offline and online.', 'images/image76.jpg', '', 0),
(77, 77, 'Which of these security questions might your bank ask you over the phone or via email?\r\n', 'To confirm your home address', 'To follow an online link to a webpage asking for your online banking log-in details', 'To give your bank card PIN', NULL, 1, 'Banks will never ask for full login or banking details and it is important to use the official website or app for online banking. They may ask you to confirm your identity by providing limited details e.g. the first line and postcode of your home address but never your full password or PIN.', 'images/image77.jpg', '', 0),
(78, 78, 'Which of the following can be useful for thieves?', 'Social media photos and posts', 'Social media biographical information', 'All of the above', NULL, 3, 'Photos and statuses can alert burglars to the fact that you’re not at home, and biographical information can be used to guess passwords or help in stealing your identity. Cybercrime is among the fastest growing and most lucrative forms of crime today. Cyber criminals use a variety of methods to steal information and deceive users into revealing personal information. While cyber criminals often use sophisticated tactics, users can significantly reduce the likelihood of victimization by following a few simple steps.', 'images/image78.jpg', '', 0),
(79, 79, 'The practice of “skimming” refers to:', 'Phony email messages asking you to support a nonexistent charity', 'Fraudulent credit card readers that steal card information', 'Fraudulent ecommerce sites that overcharge credit cards', NULL, 2, 'Skimming devices can be attached to machines with credit card readers, and portable skimmers can be used to quickly swipe a card to obtain its information.', 'images/image79.jpg', '', 0),
(80, 80, 'Smartphone apps most commonly commit fraud by', 'Stealing credit card information', 'Simulating ad interactions to scam advertisers\r\n', 'Monitoring your browsing activity to steal passwords', NULL, 2, 'Advertising scams are the most common and lucrative form of app fraud.', 'images/image80.jpg', '', 0),
(81, 81, 'A computer virus behaves in what manner:', 'Spreads quickly across a computer network', 'Hijacks video and audio software to monitor your actions', 'Hides in a program and replicates itself to as many files as possible on a computer', NULL, 3, 'Viruses attempt to spread from file to file, but they generally have difficulty spreading across computers.', 'images/image81.jpg', '', 0),
(82, 82, 'Viruses commonly originate from:', 'Malicious programs downloaded from suspicious sources and predatory online ads', 'Online radios', 'Illegally viewed videos, like theatrical releases', NULL, 1, 'While viruses can originate from a variety of sources, they most commonly occur when users download harmful software from untrustworthy sources.', 'images/image82.jpg', '', 0),
(83, 83, 'What is Ransomware?', 'Steals sensitive or personal files and sells them to the highest bidder', 'Prevents users from accessing their machines and demands a payment to restore a machine’s usability', 'Collects the contact information of family and friends to notify them that you’ve been kidnapped and demand payment', NULL, 2, 'Ransomware is a form of sophisticated malware that prevents users from accessing their files and demands payment to restore access.', 'images/image83.jpg', '', 0),
(84, 84, 'Which security feature on your smartphone do you need to set up yourself?', 'A strong password', 'Device encryption', 'Native (pre-installed) app security', NULL, 1, 'Both Apple and Android provide several options for password entry to access their phones, but they do not require users to set up password entry.', 'images/image84.jpg', '', 0),
(85, 85, 'What is the recommended minimum length for a strong password?', '8 characters\r\n', '5 characters', 'No length restrictions', NULL, 1, 'Password strength is a measure of the effectiveness of a password against guessing or brute-force attacks. In its usual form, it estimates how many trials an attacker who does not have direct access to the password would need, on average, to guess it correctly. The strength of a password is a function of length, complexity, and unpredictability', 'images/image85.jpg', '', 0),
(86, 86, 'Which of the following is the transforming of data into an unreadable format that seems to be not readily understandable, so as to hide it from outsiders?', 'Digital Certificate', 'Encryption', 'HTTP', NULL, 2, 'The word encryption comes from the Greek word kryptos, meaning hidden or secret. The use of encryption is nearly as old as the art of communication itself. As early as 1900 BC, an Egyptian scribe used non-standard hieroglyphs to hide the meaning of an inscription. In a time when most people couldn\'t read, simply writing a message was often enough, but encryption schemes soon developed to convert messages into unreadable groups of figures to protect the message\'s secrecy while it was carried from one place to another. The contents of a message were reordered (transposition) or replaced (substitution) with other characters, symbols, numbers or pictures in order to conceal its meaning.', 'images/image86.jpg', '', 0),
(87, 87, 'Which of these passwords is the most secure?', 'Orange25Mango', 'SNL*17', 'Kil2OL^Sereng8i', NULL, 3, 'Kil2OLriz^Serg8i, is the most secure – it is both long and complex.\r\nLong = 12+ characters\r\nComplex = at least one lower case, upper case, number, and special characters\r\nPassword cracking tools have massive dictionaries that include not just words, but numbers, symbols, and common combinations, like p@55word. These make most passwords unnervingly easy and fast to crack. To increase your security, make your passwords as long, complex, and unique as possible.', 'images/image87.jpg', '', 0),
(88, 88, 'Why does enabling Two Factor Authentication increase your security?', 'Forces you to have a password longer than 5 characters', 'Requires \"something you know\" and \"something you have\" to log into your account\r\n', 'Allows you to unlock your phone by taking two consecutive selfies', NULL, 2, 'Two Factor Authentication requires something you know – a password – with something you have – usually your phone.\r\nThink of it as double-checking that you are you. When you log into an account, you’ll enter your password, which will prompt a code to be sent to your phone. Simply enter the code you received and you’re in!\r\nThis way, even if someone has your password, they can’t get into your account without the code from your phone.\r\nWhile this may seem like a hassle, it is significantly faster than changing all of your passwords often enough to deter an attacker. Not to mention the time, information, and privacy loss if your account was compromised.', 'images/image88.jpg', '', 0),
(90, 90, 'How does spyware infect a computer?\r\n<br>A.Popups\r\n<br>B.Theft of Personal Info\r\n<br>C.Recording Web Info', 'Only A', 'Only A and B', 'All A,B and C', NULL, 3, 'Spyware is software that is installed on a computing device without the end user\'s knowledge. Such software is controversial because even though it is sometimes installed for relatively innocuous reasons, it can violate the end user\'s privacy and has the potential to be abused.', 'images/image90.jpg', '', 0);
INSERT INTO `quiz` (`question_id`, `question_no`, `question_name`, `option1`, `option2`, `option3`, `option4`, `correct_option`, `complete_answer`, `image_path`, `question_categary`, `question_level`) VALUES
(91, 91, 'How does identity theft cause problems for online users?\r\n<br>A. Steals social security\r\n<br>B. Locates where you live and all information \r\n<br>C. Steals bank information', 'Only A', 'Only A and B', 'All A,B and C', NULL, 3, 'Identity theft is a crime whereby criminals impersonate individuals, usually for financial gain. In today\'s society, you often need to reveal personal bits of information about yourself, such as your social security number, signature, name, address, phone number, cell number or even banking and credit card information. If a thief is able to access this personal information, he or she can use it to commit fraud in your name.', 'images/image91.jpg', '', 0),
(96, 96, 'This type of software is on computers and collects small pieces of information from users. It is also difficult to detect, what is it?', 'Spam', 'Malware', 'Spyware', NULL, 3, 'Spyware is software that is installed on a computing device without the end user\'s knowledge. Such software is controversial because even though it is sometimes installed for relatively innocuous reasons, it can violate the end user\'s privacy and has the potential to be abused.\r\n\r\n\r\n', 'images/image96.jpg', '', 0),
(97, 97, 'Many malware programs gather information that leads to loss of privacy. How can you generally be protected from this?', 'Close window', 'Anti-Virus Program', 'Turn Off and never use your computer', NULL, 2, 'Antivirus or anti-virus software, sometimes known as anti-malware software, is computer software used to prevent, detect and remove malicious software', 'images/image97.jpg', '', 0),
(98, 98, 'How do you protect your computer from unauthorised access at Wi-Fi hotspots?', 'I am sure it is safe enough if nobody is looking at my screen.', 'I use a firewall programme and have disabled file sharing on my computer.', 'I make sure I log off after accessing my Internet Banking account. This is sufficient to protect my computer.', NULL, 2, 'A personal firewall is a small programme that protects your computer and its contents from access by other Internet users. When installed, it stops unauthorised traffic to and from your PC. Always keep the firewall on and disable file sharing when using public Wi-Fi.', 'images/image98.jpg', '', 0),
(99, 99, 'What are cookies?', 'Food items', 'A malicious file placed on your computer by tainted websites', 'A small text file that is place on your computer’s hard drive by websites that you visit.', NULL, 3, 'Definition of: cookie. cookie. A small text file (up to 4KB) created by a website that is stored in the user\'s computer either temporarily for that session only or permanently on the hard disk (persistent cookie). Cookies provide a way for the website to recognize you and keep track of your preferences.\r\n', 'images/image99.jpg', '', 0),
(100, 100, 'What are vulnerabilities?', 'Malicious software designed to intercept or take partial control of a computer’s operation', 'Malicious code that includes viruses, worms, and Trojan horses.', 'Flaws in computer software that creates weaknesses in the overall security of the computer or network', NULL, 3, 'a vulnerability is a weakness which allows an attacker to reduce a system\'s information assurance. Vulnerability is the intersection of three elements: a system susceptibility or flaw, attacker access to the flaw, and attacker capability to exploit the flaw.', 'images/image100.jpg', '', 0),
(101, 0, 'What is the name of the software tool used to crack a single account on Netware Servers using a\r\ndictionary attack?', 'NPWCrack', 'NWPCrack', 'NovCrack', 'CrackNov', 2, 'NWPCrack is the software tool used to crack single accounts on Netware servers.', NULL, NULL, NULL),
(102, 0, 'How can you determine if an LM hash you extracted contains a password that is less than 8\r\ncharacters long?', 'There is no way to tell because a hash cannot be reversed', 'The right most portion of the hash is always the same', 'The hash always starts with AB923D', 'A portion of the hash will be all 0\'s', 2, 'When loosheets at an extracted LM hash, you will sometimes observe that the right most portion\r\nis always the same. This is padding that has been added to a password that is less than 8\r\ncharacters long.', NULL, NULL, NULL),
(103, 0, 'Several of your co-workers are having a discussion over the etc/passwd file. They are at odds\r\nover which types of encryption can not be used to secure Linux passwords.', 'Linux passwords can be encrypted with MD5', 'Linux passwords can be encrypted with SHA', 'Linux passwords can be encrypted with DES', 'Linux passwords can be encrypted with Blowfish', 2, 'Linux passwords can be encrypted with several types of hashing algorithms. These include SHQ,\r\nMD5, and Blowfish.', NULL, NULL, NULL),
(104, 0, 'Which of the following is not one of the two basic types of attacks?', 'DoS', 'Cracsheets', 'Sniffing', 'Active', 4, 'Passive and active attacks are the two basic types of attacks.', NULL, NULL, NULL),
(105, 0, 'When discussing passwords, what is considered a brute force attack?', 'You attempt every single possibility until you exhaust all possible combinations or discover the\r\npassword', 'You threaten to use the rubber hose on someone unless they reveal their password', 'You load a dictionary of words into your cracsheets program', 'You wait until the password expires', 1, 'Brute force cracsheets is a time consuming process where you try every possible combination of\r\nletters, numbers, and characters until you discover a match.', NULL, NULL, NULL),
(106, 0, 'Which of the following are well know password-cracsheets programs?', 'L0phtcrack', 'NetCat', 'Jack the Ripper', 'Netbus', 1, 'L0phtcrack and John the Ripper are two well know password-cracsheets programs. Netcat is\r\nconsidered the Swiss-army knife of hacsheets tools, but is not used for password cracsheets', NULL, NULL, NULL),
(107, 0, 'Telnet <IP Address> <Port 80>\r\nHEAD /HTTP/1.0\r\n<Return>\r\n<Return>', 'This command returns the home page for the IP address specified', 'This command opens a backdoor Telnet session to the IP address specified', 'This command returns the banner of the website specified by IP address', 'This command allows a hacker to determine the sites security', 3, 'This command is used for banner grabbing. Banner grabbing helps identify the service and\r\nversion of web server running.', NULL, NULL, NULL),
(108, 0, 'what is the next step to be performed after footprinting?', 'Enumeration', 'Scanning', 'System Hacsheets', 'Social Engineering', 2, 'Once footprinting has been completed, scanning should be attempted next. Scanning should take\r\nlace on two distinct levels: network and host.', NULL, NULL, NULL),
(109, 0, 'NSLookup is a good tool to use to gain additional information about a target network. What does\r\nthe following command accomplish?\r\nnslookup\r\n> server <ipaddress>\r\n> set type =any\r\n> ls -d <target.com>', 'Enables DNS spoofing', 'Loads bogus entries into the DNS table', 'Verifies zone security', 'Performs a zone transfer', 4, 'If DNS has not been properly secured, the command sequence displayed above will perform a\r\nzone transfer.', NULL, NULL, NULL),
(110, 0, 'While footprinting a network, what port/service should you look for to attempt a zone transfer?', '53 UDP', '53 TCP', '25 UDP', '25 TCP', 2, 'IF TCP port 53 is detected, the opportunity to attempt a zone transfer is there.', NULL, NULL, NULL),
(111, 0, 'Which of the following statements about a zone transfer is not correct?', 'A zone transfer is accomplished with the DNS', 'A zone transfer is accomplished with the nslookup service', 'A zone transfer passes all zone information that a DNS server maintains', 'A zone transfer passes all zone information that a nslookup server maintains', 2, 'Securing DNS servers should be a priority of the organization. Hackers obtaining DNS\r\ninformation can discover a wealth of information about an organization. This information can be\r\nused to further exploit the network.', NULL, NULL, NULL),
(112, 0, 'Which of the following tools are used for enumeration?', 'USER2SID', 'Cheops', 'SID2USER', 'DumpSec', 2, 'USER2SID, SID2USER, and DumpSec are three of the tools used for system enumeration.\r\nOthers are tools such as NAT and Enum. Knowing which tools are used in each step of the\r\nhacsheets methodology is an important goal of the CEH exam. You should spend a portion of\r\nyour time preparing for the exam practicing with the tools and learning to understand their output.', NULL, NULL, NULL),
(113, 0, 'When worsheets with Windows systems, what is the RID of the true administrator account?', '500', '501', '1000', '1001', 1, 'Because of the way in which Windows functions, the true administrator account always has a RID\r\nof 500.', NULL, NULL, NULL),
(114, 0, 'The follows is an email header. What address is that of the true originator of the message?\r\nReturn-Path: <bgates@microsoft.com>\r\nReceived: from smtp.com (fw.emumail.com [215.52.220.122].\r\nby raq-221-181.ev1.net (8.10.2/8.10.2. with ESMTP id h78NIn404807\r\nfor <mikeg@thesolutionfirm.com>; Sat, 9 Aug 2003 18:18:50 -0500\r\nReceived: (qmail 12685 invoked from network.; 8 Aug 2003 23:25:25 -0000\r\nReceived: from ([19.25.19.10].\r\nby smtp.com with SMTP\r\nReceived: from unknown (HELO CHRISLAPTOP. (168.150.84.123.\r\nby localhost with SMTP; 8 Aug 2003 23:25:01 -0000\r\nFrom: \"Bill Gates\" <bgates@microsoft.com>\r\nTo: \"mikeg\" <mikeg@thesolutionfirm.com>\r\nSubject: We need your help!\r\nDate: Fri, 8 Aug 2003 19:12:28 -0400\r\nMessage-ID: <51.32.123.21@\r\nMIME-Version: 1.0\r\nContent-Type: multipart/mixed;\r\nboundary=\"----=_NextPart_000_0052_01C35DE1.03202950\"\r\nX-Priority: 3 (Normal.\r\nX-MSMail-Priority: Normal\r\nX-Mailer: Microsoft Outlook, Build 10.0.2627\r\nX-MimeOLE: Produced By Microsoft MimeOLE V6.00.2800.1165\r\nImportance: Normal', '19.25.19.10', '51.32.123.21', '168.150.84.123', '215.52.220.122', 3, 'Spoofing can be easily achieved by manipulating the \"from\" name field, however, it is much more\r\ndifficult to hide the true source address. The \"received from\" IP address 168.150.84.123 is the\r\ntrue source of the', NULL, NULL, NULL),
(115, 0, 'What is the tool Firewalk used for?', 'To exam the IDS for proper operation', 'To exam a firewall for proper operation', 'To determine what rules are in place for a firewall', 'Firewalk is a firewall auto configuration tool', 3, 'Firewalk is an active reconnaissance network security tool that attempts to determine what layer\r\n4 protocols a given IP forwarding device \"firewall\" will pass. Firewalk works by sending out TCP\r\nor UDP packets with a TTL one greater than the targeted gateway. If the gateway allows the\r\ntraffic, it will forward the packets to the next hop where they will expire and elicit an\r\nICMP_TIME_EXCEEDED message. If the gateway host does not allow the traffic, it will likely\r\ndrop the packets and no response will be returned.', NULL, NULL, NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `quiz`
--
ALTER TABLE `quiz`
  ADD PRIMARY KEY (`question_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `quiz`
--
ALTER TABLE `quiz`
  MODIFY `question_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=116;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
